import { ScheduleRule } from './types';

export const defaultRules: ScheduleRule[] = [
  {
    id: 'max_weekly_hours',
    name: 'Savaitės valandų limitas',
    description: 'Per savaitę negalima viršyti nurodyto valandų skaičiaus (suminė darbo laiko apskaita)',
    type: 'max_weekly_hours',
    enabled: true,
    severity: 'error',
    params: { hours: 55.5 },
    builtIn: true,
  },
  {
    id: 'min_rest_days',
    name: 'Minimalus poilsis tarp budėjimų',
    description: 'Tarp dviejų budėjimų turi būti nurodytas minimalus poilsio dienų skaičius',
    type: 'min_rest_days',
    enabled: true,
    severity: 'error',
    params: { days: 2 },
    builtIn: true,
  },
  {
    id: 'no_polyclinic_same_day',
    name: 'Poliklinikos dienos konfliktas',
    description: 'Gydytojas negali budėti tą dieną, kai dirba poliklinikoje',
    type: 'no_polyclinic_same_day',
    enabled: true,
    severity: 'error',
    params: {},
    builtIn: true,
  },
  {
    id: 'no_polyclinic_prev_day',
    name: 'Dieną prieš polikliniką',
    description: 'Gydytojas negali budėti dieną PRIEŠ poliklinikos dieną (budėjimas trunka iki 8:00 ryto)',
    type: 'no_polyclinic_prev_day',
    enabled: true,
    severity: 'error',
    params: {},
    builtIn: true,
  },
  {
    id: 'require_both_slots',
    name: 'Abu stulpeliai užpildyti',
    description: 'Kiekviena diena turi turėti gydytoją ir už respubliką (R), ir už skyrių (D)',
    type: 'require_both_slots',
    enabled: true,
    severity: 'error',
    params: {},
    builtIn: true,
  },
  {
    id: 'respect_unavailable',
    name: 'Negalimos datos',
    description: 'Gerbti gydytojų pažymėtas negalimas datas (atostogos, nedarbingumas)',
    type: 'respect_unavailable',
    enabled: true,
    severity: 'error',
    params: {},
    builtIn: true,
  },
  {
    id: 'respect_slot_types',
    name: 'Stulpelių apribojimai',
    description: 'Gerbti gydytojų galimybes: kas gali budėti už respubliką, kas tik už skyrių',
    type: 'respect_slot_types',
    enabled: true,
    severity: 'error',
    params: {},
    builtIn: true,
  },
  {
    id: 'respect_monthly_limits',
    name: 'Mėnesiniai limitai',
    description: 'Gerbti gydytojų nustatytus maksimalius budėjimų skaičius per mėnesį',
    type: 'respect_monthly_limits',
    enabled: true,
    severity: 'error',
    params: {},
    builtIn: true,
  },
  {
    id: 'balance_distribution',
    name: 'Tolygus paskirstymas',
    description: 'Perspėti jei budėjimai paskirstyti netolygiai tarp gydytojų',
    type: 'balance_distribution',
    enabled: true,
    severity: 'warning',
    params: { threshold: 2.5 },
    builtIn: true,
  },
  {
    id: 'dept_only_priority',
    name: 'Skyriaus gydytojų pirmenybė',
    description: 'Gydytojai kurie gali budėti TIK už skyrių gauna pirmenybę D stulpelyje',
    type: 'dept_only_priority',
    enabled: true,
    severity: 'warning',
    params: {},
    builtIn: true,
  },
  {
    id: 'max_weekend_shifts',
    name: 'Max savaitgalio budėjimų',
    description: 'Maksimalus savaitgalio/švenčių budėjimų skaičius vienam gydytojui per mėnesį',
    type: 'max_weekend_shifts',
    enabled: true,
    severity: 'warning',
    params: { maxShifts: 4 },
    builtIn: true,
  },
];
